[theme]
base = "dark"
primaryColor = "#E76F51"             # Vibrant orange-red (for buttons/highlights)
backgroundColor = "#2E1F1A"          # Dark cocoa brown background
secondaryBackgroundColor = "#4B2E2B" # Mocha brown (containers, sidebar)
textColor = "#FFD7B5"                # Creamy latte (warm text)
font = "sans serif"
