[theme]
base="light"

primaryColor="#8B5E3C"              # Warm coffee brown (for buttons and accents)
backgroundColor="#FAF3E0"           # Creamy beige background
secondaryBackgroundColor="#FFF5D7"  # Soft yellow-tan boxes
textColor="#4E342E"                 # Deep espresso text
font="serif"