[theme]
base = "light"
primaryColor = "#6F4E37"         # Coffee brown for buttons and accents
backgroundColor = "#FFF8F0"      # Light latte background
secondaryBackgroundColor = "#C49E85"  # Caramel beige for containers
textColor = "#3B3B3B"            # Dark gray text
font = "sans serif"              # You can change to "monospace", "serif", etc.
