[theme]
base = "light"
primaryColor = "#4F6D7A"            # Calm blue
backgroundColor = "#F5F7FA"         # Light gray
secondaryBackgroundColor = "#E3E9ED"
textColor = "#2C3E50"               # Dark slate for visibility
font = "sans serif"
