[theme]
base = "light"  # Required, but we override the feel with warm custom colors
primaryColor = "#6F4E37"            # Coffee brown (buttons, highlights)
backgroundColor = "#FFF8F0"         # Latte beige (full background)
secondaryBackgroundColor = "#D7B49E" # Soft caramel (containers, sidebar)
textColor = "#3B3B3B"               # Charcoal grey (text)
font = "sans serif"
