[theme]
base = "dark"
primaryColor = "#00bcd4"              # Sky blue (button color)
backgroundColor = "#0f0f0f"           # Dark black background
secondaryBackgroundColor = "#1a1a1a"  # Slightly lighter dark for containers
textColor = "#f1f1f1"                 # Soft white text
font = "sans serif"
