[theme]
base = "dark"
primaryColor = "#FF7F50"             # Coral orange (eye-catching buttons)
backgroundColor = "#1E1410"          # Deep espresso brown
secondaryBackgroundColor = "#3B2F2A" # Dark roasted mocha
textColor = "#FBE9D0"                # Soft cream (warm, readable)
font = "sans serif"
