[theme]
base = "light"  # Required, but we override the visual with warm orange tones
primaryColor = "#E76F51"            # Vibrant orange-red (buttons, accents)
backgroundColor = "#FFF3E0"         # Light peach-orange background (like blur + sun)
secondaryBackgroundColor = "#FAD7B5" # Creamy light orange (cards, containers)
textColor = "#3B3B3B"               # Charcoal gray (for contrast)
font = "sans serif"
